### ISSUE TITLE
Create DOI for repo

### ISSUE THREAD

**Issue by mkiang** [mbjoseph/CARstan#2]
Thanks for setting up this demo. It's very helpful! I'm may potentially use it for some dissertation work. Obviously, citation is possible without a `doi`, but it would make it easier for me (and other researchers) if one was attached.

Any chance you can make that happen? There's [a Github guide on it](https://guides.github.com/activities/citable-code/).

**Comment by mbjoseph** [comment]
Sure thing, here you go: https://doi.org/10.5281/zenodo.210407

Glad it was useful! Good luck with your dissertation.
